# docker-compose.yml
version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn trackit.wsgi:application --bind 0.0.0.0:8000"
